

function RevenueModelDesc() {
  return (
    <div className="flex items-center justify-center px-4 py-5">
        <div className="flex flex-col items-center gap-10">
            <h1 className="md:text-4xl text-2xl text-white font-bold">Revenue Share Model</h1>
            <div className="flex flex-col items-center gap-5">
                <p>Token Growth Amplifier</p>
                <p className="text-white text-justify md:text-center font-bold md:w-[70vw]">The “Token Growth Amplifier” is an innovative revenue-sharing model implemented by Rentals. Under this model, 30% of the revenue generated by the platform is directly invested in purchasing Rentals (RNT) tokens from the market. This investment has several positive implications for the platform and its users.</p>
            </div>
            <p>How Token Growth Amplifier Works</p>
            
        </div>
    </div>
  )
}

export default RevenueModelDesc
