export {default as Home} from "./Home"
export {default as Platform} from "./Platform"
export {default as Contact} from "./Contact"
export {default as Acquisition} from "./Acquisition"
export {default as About} from "./About"
export {default as NewsSingle} from "./NewsSingle.tsx"