export {default as Navbar} from "./shared/Navbar"
export {default as Footer} from "./shared/Footer"
export {default as HeroDesc} from "./home/hero/HeroDesc"
export {default as HeroTabs} from "./home/hero/HeroTabs"
export {default as LatestNews} from "./home/latestNews/LatestNews"