import rentals from "@/assets/Images/homeImages/rentals.webp"
import phase from "@/assets/Images/homeImages/phase.webp"
import migration from "@/assets/Images/homeImages/migration.webp"

interface SectionBase {
  title: string;
  content: string;
}

interface SectionWithDetails extends SectionBase {
  details?: string[];
}

interface SectionWithFeatures extends SectionBase {
  features?: string[];
}

type Section = SectionBase | SectionWithDetails | SectionWithFeatures;

interface NewsData {
  id: number;
  title: string;
  date: string;
  readTime: string;
  description: string;
  image: string;
  content: {
    introduction: string;
    sections: Section[];
  };
}

const NewsData = [
  {
    "id": 1,
    "title": "RENTALS DIGITAL: The cryptocurrency that is set to revolutionize the travel and tourism industry",
    "date": "21 Nov 2024",
    "readTime": "4 Min Reads",
    "description": "The Rentals ecosystem opens its first presale phase, offering 5% rewards for referrals to incentivize early supporters.",
    "image": rentals,
    "content": {
      "introduction": "Blockchain technology and, consequently, cryptocurrencies, have transformed the traditional financial system and expanded into various sectors worldwide. However, the travel and tourism industry is one of the few that has shown slower adoption of this innovation. This billion-dollar industry still operates largely with traditional systems that are inefficient and offer few rewards for travelers and tourists. Fortunately, a new blockchain platform, called Rentals Digital, aims to change this by introducing an innovative blockchain-based ecosystem to the travel and tourism sector.",
      "sections": [
        {
          "title": "A Revolution in the Travel Experience",
          "content": "Rentals seeks to revolutionize several aspects of the travel experience within a single ecosystem. Leveraging blockchain technology, the platform simplifies booking and payment processes, ensures transparency through authentic customer reviews, and rewards users for their activities and interactions on the platform."
        },
        {
          "title": "Token Growth System: RENTS",
          "content": "The \"Token Growth Amplifier\" is an innovative revenue-sharing model implemented by Rentals. In this model, 30% of the revenue generated by the platform is directly invested in purchasing Rentals (RENTS) tokens from the market. This reinvestment brings several advantages for both the platform and its users.",
          "details": [
            "Increased Volume and Liquidity: Regular purchases of RENTS tokens increase transaction volume and market liquidity, facilitating easier trading.",
            "Token Appreciation: The ongoing increase in demand and purchases of RENTS tokens helps drive up the token's value, benefiting all investors and platform participants.",
            "Investor Confidence: The transparency of the model and the direct link between platform revenue and token appreciation creates a virtuous cycle, promoting greater engagement and trust in the Rentals ecosystem."
          ]
        },
        {
          "title": "Utility Token",
          "content": "RENTS is a BEP-20 token used as a payment method for various products and services within the Rentals Digital ecosystem. This token offers significant benefits, eliminating the need for travelers to use traditional credit cards that expose their details to third-party companies.",
          "details": [
            "No transaction limits, allowing users to make multiple payments at their holiday destinations.",
            "Cross-border transactions are much cheaper compared to the high fees associated with credit cards.",
            "Holders can also speculate on the currency and potentially earn significant profits."
          ]
        }
      ]
    }
  },
  {
    "id": 2,
    "title": "RENTALS is revolutionizing the tourism industry with innovative blockchain-based solutions",
    "date": "21 Nov 2024",
    "readTime": "4 Min Reads",
    "description": "Rentals increases referral rewards to 8% and adds a new payment method for smoother transactions.",
    "image": phase,
    "content": {
      "introduction": "Cryptocurrency meets the travel industry through RENTS. The platform's mission is to create a digital tourism solution using blockchain technology. This portal will allow users to make payments for travel services using cryptocurrencies. “Crypto meets the real world” with RENTALS. The goal of Rentals is to transform the tourism industry by becoming the primary portal where travelers can book their trips using cryptocurrencies.",
      "sections": [
        {
          "title": "RENTALS will transform the future of tourism",
          "content": "RENTALS DIGITAL aims to integrate tourism with cryptocurrencies. The team is working on launching its own coin, expected in the first quarter of 2025. The platform’s goal is to reduce international money transfer costs and simplify the use of local currency at the destination, allowing travelers to use RENTS tokens in any country."
        },
        {
          "title": "Functionality of the Platform",
          "content": "Once completed, Rentals Digital promises to function as a payment system similar to credit cards and POS terminals at vendors and establishments in selected destinations. The platform will enable users to book trips and make payments at travel service providers using RENTS tokens.",
          "details": [
            "Global B2B-B2C tourism platform using RENTS tokens.",
            "Quick and secure payments using cryptocurrency.",
            "Ability to exchange other currencies and tokens for RENTS easily and quickly."
          ]
        },
        {
          "title": "Why Choose RENTS?",
          "content": "The primary aim of Rentals Digital is to revolutionize tourism with a cryptocurrency-driven platform. RENTS token will enable seamless transactions and offer a better experience than traditional payment methods, such as credit cards, by eliminating international transfer fees and simplifying currency usage at destinations."
        }
      ]
    }
  }
  ,
  {
    "id": 3,
    "title": "Rentals Digital: Revolutionizing Tourism with Blockchain Technology",
    "date": "21 Nov 2024",
    "readTime": "4 Min Reads",
    "description": "The Rentals beta platform is now live, offering a preview of the ecosystem. Users who purchased via presale can migrate.",
    "image": migration,
    "content": {
      "introduction": "Rentals Digital is a blockchain-based ecosystem that emerges as an innovative proposal, challenging traditional paradigms in the tourism industry by leveraging the potential of an ever-evolving technology. Touted as a game-changer in the sector, the project offers a disruptive solution that promises to bring greater autonomy to various market stakeholders.",
      "sections": [
        {
          "title": "Rentals Digital Ecosystem",
          "content": "The Rentals ecosystem comprises the Rents (RENTS) token, the upcoming RENTALS DIGITAL APP, and the comprehensive RENTALS Dashboard, designed to be a hub of integrated resources. Its ability to democratize access to decentralization in tourism is one of the features that make the Rentals Project unique and promising."
        },
        {
          "title": "Blockchain Adoption in the Tourism Industry",
          "content": "The adoption and impact of blockchain technology have grown exponentially in recent years, with companies across various sectors exploring its functionalities and benefits. However, in the billion-dollar tourism industry, many blockchain-based solutions fail to effectively meet the demands of service providers and customers, often due to technical complexities. Rentals Digital aims to simplify the use of blockchain in tourism."
        },
        {
          "title": "Key Features of the Rentals Digital Platform",
          "content": "The Rentals Digital Platform is an integral part of the Rentals ecosystem, featuring tools designed to help users access the ecosystem’s incredible benefits from any smart mobile device, regardless of their location. The platform’s key features include:",
          "features": [
            "Hotel search and booking",
            "Rents token wallet",
            "Service pricing based on RENTS tokens",
            "Information about RENTS token rewards",
            "RENTS partner map",
            "RENTS transactions via QR codes",
            "Friends list",
            "Customer reviews",
            "Management of services based on RENTS tokens",
            "Customer messaging",
            "Purchase of RENTS tokens",
            "Premium services",
            "Rewards for loyal customers",
            "Targeted notifications",
            "Advertising on the platform"
          ]
        }
      ]
    }
  }
  
  ]
  

  
  export default NewsData;